package NumberGuessingGame2;

import javax.swing.*;

public class MyJFrame extends JFrame {

    private Zahlenraten game = null;
    /**
     * Creates new form NewJFrame
     */
    public MyJFrame() {
        initComponents();
        game = new Zahlenraten();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        panel = new javax.swing.JPanel();
        labelMinZahl = new javax.swing.JLabel();
        labelMaxZahl = new javax.swing.JLabel();
        textMinZahl = new javax.swing.JTextField();
        textMaxZahl = new javax.swing.JTextField();
        buttonUnit = new javax.swing.JButton();
        textConsole = new javax.swing.JTextField();
        textZahl = new javax.swing.JTextField();
        buttonGame = new javax.swing.JButton();
        buttonEndGame = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 400));

        panel.setPreferredSize(new java.awt.Dimension(400, 400));

        labelMinZahl.setText("untere Intervalgrenze");

        labelMaxZahl.setText("obere Intervalgrenze");

        textMinZahl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMinZahlActionPerformed(evt);
            }
        });

        textMaxZahl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMaxZahlActionPerformed(evt);
            }
        });

        buttonUnit.setText("Unit");
        buttonUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUnitActionPerformed(evt);
            }
        });

        textConsole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textConsoleActionPerformed(evt);
            }
        });

        textZahl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textZahlActionPerformed(evt);
            }
        });

        buttonGame.setText("Spielen");
        buttonGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGameActionPerformed(evt);
            }
        });

        buttonEndGame.setText("Beenden");
        buttonEndGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEndGameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
                panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(textConsole)
                                        .addComponent(textZahl)
                                        .addGroup(panelLayout.createSequentialGroup()
                                                .addComponent(buttonGame)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(buttonEndGame))
                                        .addGroup(panelLayout.createSequentialGroup()
                                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(labelMinZahl)
                                                        .addComponent(labelMaxZahl))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(textMinZahl, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(textMaxZahl, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(43, 43, 43)))
                                .addGap(62, 62, 62))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonUnit)
                                .addGap(120, 120, 120))
        );
        panelLayout.setVerticalGroup(
                panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textMinZahl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(labelMinZahl))
                                .addGap(27, 27, 27)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(textMaxZahl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(labelMaxZahl))
                                .addGap(18, 18, 18)
                                .addComponent(buttonUnit)
                                .addGap(32, 32, 32)
                                .addComponent(textConsole, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(textZahl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(buttonGame)
                                        .addComponent(buttonEndGame))
                                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void textMinZahlActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void textMaxZahlActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void buttonUnitActionPerformed(java.awt.event.ActionEvent evt) {
        int min = 0;
        int max = 10;
        min = Integer.parseInt(textMinZahl.getText());
        max = Integer.parseInt(textMaxZahl.getText());
        game.setMinZahl(min);
        game.setMaxZahl(max);
    }

    private void textConsoleActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void textZahlActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void buttonGameActionPerformed(java.awt.event.ActionEvent evt) {
        if(game != null){
            game.start();
        }
    }

    private void buttonEndGameActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }


    // Variables declaration - do not modify
    private javax.swing.JButton buttonEndGame;
    private javax.swing.JButton buttonGame;
    private javax.swing.JButton buttonUnit;
    private javax.swing.JLabel labelMaxZahl;
    private javax.swing.JLabel labelMinZahl;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField textConsole;
    private javax.swing.JTextField textMaxZahl;
    private javax.swing.JTextField textMinZahl;
    private javax.swing.JTextField textZahl;
    // End of variables declaration
}
